  version: "3.9" 
  
  services: 
    app: 
      build: . 
      restart: always 
      environment: 
        SQLALCHEMY_DATABASE_URI: postgresql://administrator:verySecretPassword@database:5432/postgres 
      ports: 
        - "8080:8080" 
      depends_on: 
        - database

    database: 
      image: postgres:latest 
      restart: always 
      environment: 
        POSTGRES_PASSWORD: verySecretPassword 
        POSTGRES_USER: administrator 
      volumes: 
        - ./data/db:/var/lib/postgresql/data 